### ISSUE TITLE
Cannot read property 'lupi' of undefined

### ISSUE THREAD

**Issue by Mattish** [tommoyang/Mahira#33]
```
Error in event handler for (unknown): TypeError: Cannot read property 'lupi' of undefined
    at Object.SetLupiCrystal (chrome-extension://pcaghccghggphnnckgegjoingiiplinm/src/background/profile.js:235:86)
    at Object.performRequestAction (chrome-extension://pcaghccghggphnnckgegjoingiiplinm/src/background/backgroundMessageActionCollection.js:50:17)
    at extensionListener (chrome-extension://pcaghccghggphnnckgegjoingiiplinm/src/background/background.js:213:51)
```

**Comment by Mattish** [comment]
[bug_1_lupi.json.txt](https://github.com/tommoyang/Mahira/files/1545670/bug_1_lupi.json.txt)

example json message which causes it to throw

**Comment by Mattish** [comment]
#34
